[package]
name = "rust-vst-tutorial"
version = "0.1.0"
authors = ["AlanSwenson <alan@alanswenson.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
